### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [cheery/lever#3]
The language seems interesting because of light syntax, FFI and its programmability. Despite it's utter slowness, I'd like to know whether there are any plans to continue?

Btw. you might be interested in [Basil](https://github.com/basilTeam/basil ) as it syntactically and with its programmability slightly resembles Lever.

**Comment by cheery** [comment]
No plans to continue on lever.

pe 7. toukok. 2021 klo 14.17 dumblob ***@***.***> kirjoitti:

**Comment by dumblob** [comment]
Ok, closing. Cheers anyway - it must have been quite a lot of effort!

**Comment by dumblob** [comment]
Btw. I finally found some time to read a few of your blog posts and I understood you were (still are?) looking for a language which seamlessly supports runtime typing ("dynamic" typing) as well as static typing (both AOT typing as "partial correctness ensurance" and AOT compilation to native binary as "performance ensurance").

If that's correct, then we share this vision :wink:. In such case you might be interested in [XL](https://github.com/c3d/xl ) ([read its history as its kind of important](https://xlr.sourceforge.io/#history-of-xl ) and see some examples of versatility: https://github.com/c3d/xl/issues/43#issuecomment-751251169 ).
